### ISSUE TITLE
Does this nice lib work with FreeRTOS?

### ISSUE THREAD

**Issue by spachner** [ThrowTheSwitch/CException#11]
Hi,

does this nice lib work with FreeRTOS, too?

regards

spachner

**Comment by mvandervoord** [comment]
Yes.

You will need to use the FreeRTOS context switch hook in order to set the
current task ID in a variable so you can define it to be fetched
by EXCEPTION_GET_ID. Then set EXCEPTION_NUM_ID to the number of tasks you
have running.

Mark
