### ISSUE TITLE
Regarding release cycle of this project

### ISSUE THREAD

**Issue by michaelbrockus** [ThrowTheSwitch/CException#22]
I was wondering if there is a plan to have more releases of the CException project or is `1.3.1` the only release available? Simply asking because I would like to add this to the Dragon WrapDB service and am just wondering if I should subscribe to this repository for any potential releases.

https://dragon-wrap.github.io/

**Comment by mvandervoord** [comment]
We occasionally add improvements or fixes... but they are few and far between. This is definitely the most stable project I'm part of... it does its one thing and it does it fairly well. No frills ;)

**Comment by michaelbrockus** [comment]
Alright then but most of those fixes would not go to the end user unfortunately do to how WrapDB databases work.

https://mesonbuild.com/Using-the-WrapDB.html

**Comment by mvandervoord** [comment]
Am I understanding correctly that you're suggesting official releases are better because they will trigger updates for people?

I agree with that. I try to push an official release whenever ceedling has a release and this project has had changes in that time. Maybe I've missed some of those opportunities?  ;)

**Comment by michaelbrockus** [comment]
With an official release of a project such as this one, it is guaranteed that the author of the package made sure everything was stable before making that release.

Hopefully, there will be new releases soon or whenever you guys feel like throwing the switch, there is at least one to work with.

**Comment by mvandervoord** [comment]
:) released. Thanks for the advice, @michaelbrockus . I appreciate it.
