### ISSUE TITLE
CException is missing a license file

### ISSUE THREAD

**Issue by swaldhoer** [ThrowTheSwitch/CException#29]
All other ThrowTheSwitch projects have a dedicate license file

- Ceedling: https://github.com/ThrowTheSwitch/Ceedling/blob/134496c6c0c34b463d58daef1904a12abdc5c8e0/license.txt
- Unity: https://github.com/ThrowTheSwitch/Unity/blob/64939db64e3271808fdfcfa348120b36790a23cf/LICENSE.txt
- CMock: https://github.com/ThrowTheSwitch/CMock/blob/9192a950897929d948027421e30a372b1770469b/LICENSE.txt

The license for CException is only stated at the end of the [README](https://github.com/ThrowTheSwitch/CException/blob/3667ee2d4428c7ca602f2a1ab925ab1a3c2c0a09/README.md#license) file of the project.

Would it be possible to add a license file to the repository? I think it make sense as it makes the information better accessible and in a more common way.

**Comment by mvandervoord** [comment]
Great point. Thanks for noticing!

**Comment by swaldhoer** [comment]
@mvandervoord Would you be willing to also include an [SPDX identifier](https://spdx.dev/) to the sources? This would make the creation of an SBOM way simpler and is not really much effort to do that on source side (and on consumer side it creates effort).

Adding SPDX identifiers is simple for licenses like `MIT`, see <https://spdx.dev/learn/handling-license-info>.

**Comment by mvandervoord** [comment]
@swaldhoer -- I've corrected the license handling. It's now consistent with the other projects.

I looked into the SPDX identifiers. It's a simple process and I definitely see a place for it. The only downside is that the required Linux Foundation membership is rather costly. I'll leave this issue open and can hopefully do this in the future.

**Comment by swaldhoer** [comment]
> @swaldhoer -- I've corrected the license handling. It's now consistent with the other projects.

perfect, thank you!

> I looked into the SPDX identifiers. It's a simple process and I definitely see a place for it. The only downside is that the required Linux Foundation membership is rather costly.

Sorry, I don't understand this point.  What is the relation between *adding a SPDX identifier to the source code* and a *required Linux Foundation membership*.
Do you mean you need to be a member of the Linux Foundation in order to be allowed to add a SPD identifer to the source code? If so, could you point me to that source? I have never read or heard of that.

**Comment by mvandervoord** [comment]
My mistake. I see the important bits of information now. When I first went to the site, it had a popup talking about membership and I assumed that was necessary. Thanks for the followup!

**Comment by swaldhoer** [comment]
Fixed in 18d020cec7daca2c2af7c48555aa3df2e077591c and df9af17159b3807b81ee7b0387af8075a535391c.
